export const data = function(){
    return [
        {
            name: "Ocean game (TEMP NAME)",
            year: "In progress",
            oneline: "An rpg",
            description: "",
            images: "",
            thumbnail: "",
            platforms: ["windows","mac"],
            links: [],
        },
        {
            name: "Rose Curve Visualizer",
            year: "2023",
            oneline: "A mesmerizing garden of animated mathematical roses, inviting exploration with playful and intuitive controls.",
            description: "This online garden transforms mathematical beauty into a fun and mesmerizing experience. Centered around the idea of exploration and play, the controls are designed to let curiosity guide the user to explore a variety of animated rose curves.",
            images: "",
            thumbnail: "",
            platforms: ["web"],
            links: [
                {title:"View now", link:"https://davetheknave.github.io/Rose-Curve-Visualizer"},
                {title:"Source code", link:"https://github.com/davetheknave/Rose-Curve-Visualizer"},
            ],
        },
        {
            name: "Personal Portfolio",
            year: "2023",
            oneline: "You're looking at it!",
            description: ``,
            images: "",
            thumbnail: "",
            platforms: ["web"],
            links: [{"title":"Source Code","link":"https://github.com/davetheknave"}],
        },
        {
            name: "Divine Law",
            year: "2021",
            oneline: "My and my sister's entry to AI and Games Jam 2021. This is a video game about an angel that defies the laws of physics to stop a serpent from breaking into the Garden of Eden.",
            description: ``,
            images: "",
            thumbnail: "noimage.png",
            platforms: ["windows","mac"],
            links: [{title:"Play now",link:"http://itch.io"}],
        },
        {
            name: "Old portfolio sites",
            year: "",
            oneline: "Previous versions of my portfolio. Kept here for digital archaeologists.",
            description: "They aren't hosted anymore, but the source code is still available.",
            images: "",
            thumbnail: "",
            platforms: ["web"],
            links: [{title: "Source code", link: "https://github.com/davetheknave"}],
        },
        {
            name: "D-Chess",
            year: "2018",
            oneline: "A five-dimensional chess game for two players that involves moving pieces into other dimensions and into the future.",
            description: "",
            images: "",
            thumbnail: "",
            platforms: ["windows","mac","linux"],
            links: [{title: "Source code", link: "https://github.com/davetheknave"}],
        },
    ]
}